# Generated by Django 5.2.15 on 2026-07-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_add_action_and_event_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramreel',
            name='permalink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
