# Generated by Django 5.2.15 on 2026-07-02 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_alter_instagramreel_permalink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionexecution',
            name='instagram_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.instagramaccount'),
        ),
    ]
